export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
export const INCREMENT_ASYNC_REQUESTED = 'counter/INCREMENT_ASYNC_REQUESTED';
export const INCREMENT = 'counter/INCREMENT';

export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
export const DECREMENT_ASYNC_REQUESTED = 'counter/DECREMENT_ASYNC_REQUESTED';
export const DECREMENT = 'counter/DECREMENT';
